# DHCP for Tor transparent proxy subnet
# Clients on 172.16.100.x have all TCP transparently routed through Tor
# Install to: /etc/dnsmasq.d/tor-ap.conf
# Only used if brcmfmac supports a second virtual AP (uap1)
# If not, clients on uap0 can manually set a 172.16.100.x static IP

interface=uap1
dhcp-range=172.16.100.10,172.16.100.100,255.255.255.0,24h
dhcp-option=interface:uap1,3,172.16.100.1
dhcp-option=interface:uap1,6,172.16.100.1
