#!/bin/bash
# install/04-dns.sh — DNS stack: stubby (DoT) and AdGuard Home
# Defines run_dns(). Source this file; do not execute directly.

run_dns() {
    # ── stubby — DNS-over-TLS ───────────────────────────────────────────────────
    section "stubby — DNS-over-TLS"

    mkdir -p /etc/stubby
    install_file config/stubby.yml /etc/stubby/stubby.yml 644

    if [[ "${ENABLE_DOT:-0}" = "1" ]]; then
        install_file config/dnsmasq-dot.conf /etc/dnsmasq.d/dot.conf
        run_or_dry systemctl enable --now stubby 2>/dev/null || true
        ok "DNS-over-TLS enabled: dnsmasq → stubby → Cloudflare/Quad9"
    else
        systemctl disable --now stubby 2>/dev/null || true
        ok "DNS-over-TLS installed but disabled (set ENABLE_DOT=1 to activate)"
    fi

    # ── AdGuard Home ─────────────────────────────────────────────────────────────
    section "AdGuard Home — DNS ad-blocker"

    local _AP_GATEWAY="${AP_GATEWAY:-10.3.141.1}"

    if [[ "${ENABLE_ADGUARD:-0}" = "1" ]]; then
        info "Downloading AdGuard Home binary..."
        if ! bash "${REPO}/scripts/install-adguard.sh"; then
            warn "AdGuard Home installation failed — check network and retry"
            warn "To retry: bash /opt/pi-travel-router/scripts/install-adguard.sh"
            ENABLE_ADGUARD=0
        else
            install_file config/AdGuardHome.yaml /opt/AdGuardHome/AdGuardHome.yaml 640
            install_file config/dnsmasq-adguard.conf /etc/dnsmasq.d/adguard.conf
            rm -f /etc/dnsmasq.d/dot.conf
            run_or_dry systemctl enable --now adguard-home 2>/dev/null || true
            ok "AdGuard Home enabled — web UI at http://${_AP_GATEWAY}:3000"
        fi
    else
        ok "AdGuard Home disabled (set ENABLE_ADGUARD=1 to activate)"
    fi

    # ── Domain-based split tunnel ────────────────────────────────────────────────
    section "Domain-based split tunnel"

    install_file scripts/apply-split-tunnel.sh /usr/local/bin/apply-split-tunnel.sh 755
    install_file systemd/split-tunnel.service /etc/systemd/system/split-tunnel.service 644
    systemctl daemon-reload

    if [[ "${ENABLE_SPLIT_TUNNEL:-0}" = "1" ]]; then
        if [[ -z "${SPLIT_TUNNEL_DOMAINS:-}" ]]; then
            warn "ENABLE_SPLIT_TUNNEL=1 but SPLIT_TUNNEL_DOMAINS is empty"
            warn "  Set SPLIT_TUNNEL_DOMAINS in /etc/default/travel-router and run:"
            warn "  sudo systemctl restart dnsmasq split-tunnel.service"
        else
            run_or_dry env DEBIAN_FRONTEND=noninteractive apt-get install -y ipset 2>/dev/null || true
            local _DOMAIN_PATH
            _DOMAIN_PATH=$(printf '%s' "$SPLIT_TUNNEL_DOMAINS" | tr ' ' '/')
            printf "# Split tunnel domains — generated by install\nipset=/%s/vpn_domains\n" \
                "$_DOMAIN_PATH" > /etc/dnsmasq.d/split-tunnel.conf
            run_or_dry systemctl enable --now split-tunnel.service 2>/dev/null || true
            systemctl restart dnsmasq 2>/dev/null || true
            ok "Split tunnel enabled — domains via Tailscale: ${SPLIT_TUNNEL_DOMAINS}"
        fi
    else
        systemctl disable split-tunnel.service 2>/dev/null || true
        rm -f /etc/dnsmasq.d/split-tunnel.conf
        ok "Split tunnel disabled (set ENABLE_SPLIT_TUNNEL=1 + SPLIT_TUNNEL_DOMAINS)"
    fi
}
