#!/usr/bin/env python3
"""First-boot setup wizard for pi-travel-router.

Listens on :80, serves a single-page HTML form, and on submit writes the user's
answers to /var/lib/travel-router/firstboot-env.sh, then spawns install.sh in
non-interactive mode. Stdlib only.
"""
from __future__ import annotations

import html
import os
import re
import shlex
import subprocess
import sys
from http import HTTPStatus
from http.server import BaseHTTPRequestHandler, HTTPServer
from urllib.parse import parse_qs

STATE_DIR = "/var/lib/travel-router"
ENV_FILE = os.path.join(STATE_DIR, "firstboot-env.sh")
DONE_FILE = os.path.join(STATE_DIR, "firstboot-done")
LOG_FILE = "/var/log/firstboot-install.log"
REPO_DIR = "/opt/pi-travel-router"
INDEX_HTML = os.path.join(os.path.dirname(os.path.abspath(__file__)), "index.html")

BOOL_FLAGS = [
    "ENABLE_VPN_KILLSWITCH",
    "ENABLE_BLOCKLISTS",
    "ENABLE_DOT",
    "ENABLE_AUTO_UPDATES",
    "ENABLE_AVAHI_REFLECTOR",
    "ENABLE_ADGUARD",
    "ENABLE_AP_SCHEDULE",
    "ENABLE_CLIENT_QOS",
    "ENABLE_CAKE_AUTOTUNE",
    "ENABLE_BANDWIDTH_DASHBOARD",
    "ENABLE_PROMETHEUS_EXPORTER",
    "ENABLE_UPS_MONITOR",
    "ENABLE_2FA",
    "ENABLE_SPLIT_TUNNEL",
    "ENABLE_WAN_METRICS",
]

STRING_FIELDS = [
    "AP_SSID",
    "AP_PASS",
    "COUNTRY",
    "NTFY_TOPIC",
    "TS_KEY",
    "SSH_ADMIN_KEY",
    "HEADSCALE_URL",
    "SPLIT_TUNNEL_DOMAINS",
]


def _first(form: dict, key: str, default: str = "") -> str:
    v = form.get(key, [default])
    return v[0] if v else default


def _validate(form: dict) -> tuple[dict, list[str]]:
    errors: list[str] = []
    values: dict[str, str] = {}

    ap_ssid = _first(form, "AP_SSID", "TravelRouter").strip()
    if not (1 <= len(ap_ssid) <= 32):
        errors.append("AP SSID must be 1-32 characters.")
    values["AP_SSID"] = ap_ssid

    ap_pass = _first(form, "AP_PASS")
    if not (8 <= len(ap_pass) <= 63):
        errors.append("AP passphrase must be 8-63 characters.")
    values["AP_PASS"] = ap_pass

    country = _first(form, "COUNTRY", "US").strip().upper()
    if not re.fullmatch(r"[A-Z]{2}", country):
        errors.append("Country code must be two letters (e.g. US).")
    values["COUNTRY"] = country

    ntfy = _first(form, "NTFY_TOPIC").strip()
    if ntfy and not re.fullmatch(r"[A-Za-z0-9._-]+", ntfy):
        errors.append("ntfy.sh topic may only contain letters, numbers, dot, underscore, dash.")
    values["NTFY_TOPIC"] = ntfy

    ts_key = _first(form, "TS_KEY").strip()
    headscale_url = _first(form, "HEADSCALE_URL").strip()
    if ts_key and not headscale_url and not ts_key.startswith("tskey-auth-"):
        errors.append("Tailscale auth key must start with tskey-auth-.")
    values["TS_KEY"] = ts_key
    values["HEADSCALE_URL"] = headscale_url

    ssh_key = _first(form, "SSH_ADMIN_KEY").strip()
    if ssh_key and not re.match(r"^(ssh-(rsa|ed25519|dss)|ecdsa-sha2-)", ssh_key):
        errors.append("SSH admin public key must be a valid OpenSSH public key.")
    values["SSH_ADMIN_KEY"] = ssh_key

    values["SPLIT_TUNNEL_DOMAINS"] = _first(form, "SPLIT_TUNNEL_DOMAINS").strip()

    for flag in BOOL_FLAGS:
        values[flag] = "1" if _first(form, flag) else "0"

    if values["ENABLE_SPLIT_TUNNEL"] == "1" and not values["SPLIT_TUNNEL_DOMAINS"]:
        errors.append("Split tunnel enabled but no domains supplied.")

    return values, errors


def _write_env_file(values: dict[str, str]) -> None:
    os.makedirs(STATE_DIR, exist_ok=True)
    lines = ["#!/bin/bash", "# Generated by firstboot wizard. Do not edit manually.", ""]
    for key in STRING_FIELDS + BOOL_FLAGS:
        if key in values:
            lines.append(f"export {key}={shlex.quote(values[key])}")
    lines.append("export INSTALL_NONINTERACTIVE='1'")
    lines.append("")
    tmp = ENV_FILE + ".tmp"
    with open(tmp, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
    os.chmod(tmp, 0o600)
    os.replace(tmp, ENV_FILE)


def _spawn_install() -> None:
    cmd = (
        f"source {shlex.quote(ENV_FILE)} && "
        f"cd {shlex.quote(REPO_DIR)} && "
        f"bash install.sh > {shlex.quote(LOG_FILE)} 2>&1 && "
        f"touch {shlex.quote(DONE_FILE)} && "
        f"systemctl disable firstboot.service && "
        f"reboot"
    )
    subprocess.Popen(
        ["nohup", "bash", "-c", cmd],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        stdin=subprocess.DEVNULL,
        start_new_session=True,
    )


def _running_page() -> bytes:
    body = """<!doctype html>
<html><head><meta charset="utf-8"><title>Travel Router — Setting up</title>
<meta http-equiv="refresh" content="5; url=/status">
<meta name="viewport" content="width=device-width,initial-scale=1">
<style>body{font-family:system-ui,sans-serif;background:#0d1117;color:#c9d1d9;margin:0;padding:2rem;max-width:640px;margin:auto}
h1{color:#58a6ff}.spin{display:inline-block;width:1em;height:1em;border:2px solid #30363d;border-top-color:#58a6ff;border-radius:50%;animation:s 1s linear infinite;vertical-align:middle;margin-right:.5rem}
@keyframes s{to{transform:rotate(360deg)}}</style></head>
<body><h1><span class="spin"></span>Setting up…</h1>
<p>This page will refresh every 5 seconds. Setup typically takes 5-10 minutes.</p>
<p>The Pi will reboot automatically when finished. Reconnect to your new SSID afterward.</p>
<p><a href="/status" style="color:#58a6ff">Check status now</a></p>
</body></html>
"""
    return body.encode("utf-8")


def _error_page(errors: list[str]) -> bytes:
    items = "".join(f"<li>{html.escape(e)}</li>" for e in errors)
    body = f"""<!doctype html>
<html><head><meta charset="utf-8"><title>Travel Router — Errors</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<style>body{{font-family:system-ui,sans-serif;background:#0d1117;color:#c9d1d9;margin:0;padding:2rem;max-width:640px;margin:auto}}
h1{{color:#f85149}}a{{color:#58a6ff}}</style></head>
<body><h1>Configuration errors</h1><ul>{items}</ul>
<p><a href="/">Back to setup</a></p></body></html>
"""
    return body.encode("utf-8")


def _status_page() -> bytes:
    done = os.path.exists(DONE_FILE)
    tail = ""
    try:
        with open(LOG_FILE, "r", encoding="utf-8", errors="replace") as fh:
            lines = fh.readlines()[-20:]
            tail = "".join(lines)
    except FileNotFoundError:
        tail = "(install log not yet created)\n"
    tail_html = html.escape(tail)
    if done:
        header = "<h1>Setup complete — rebooting</h1><p>Reconnect to your new Wi-Fi SSID. This page will not respond after the reboot.</p>"
        refresh = ""
    else:
        header = '<h1><span class="spin"></span>Still installing…</h1><p>Last 20 lines of the installer log:</p>'
        refresh = '<meta http-equiv="refresh" content="5; url=/status">'
    body = f"""<!doctype html>
<html><head><meta charset="utf-8"><title>Travel Router — Status</title>
{refresh}
<meta name="viewport" content="width=device-width,initial-scale=1">
<style>body{{font-family:system-ui,sans-serif;background:#0d1117;color:#c9d1d9;margin:0;padding:2rem;max-width:760px;margin:auto}}
h1{{color:#58a6ff}}pre{{background:#161b22;border:1px solid #30363d;border-radius:6px;padding:1rem;overflow:auto;font-size:.85em}}
.spin{{display:inline-block;width:1em;height:1em;border:2px solid #30363d;border-top-color:#58a6ff;border-radius:50%;animation:s 1s linear infinite;vertical-align:middle;margin-right:.5rem}}
@keyframes s{{to{{transform:rotate(360deg)}}}}</style></head>
<body>{header}<pre>{tail_html}</pre></body></html>
"""
    return body.encode("utf-8")


class Handler(BaseHTTPRequestHandler):
    server_version = "TravelRouterFirstBoot/1.0"

    def log_message(self, format, *args):  # noqa: A002
        sys.stderr.write("[firstboot] " + (format % args) + "\n")

    def _send(self, status: int, body: bytes, content_type: str = "text/html; charset=utf-8") -> None:
        self.send_response(status)
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-store")
        self.end_headers()
        self.wfile.write(body)

    def do_GET(self):  # noqa: N802
        if self.path == "/" or self.path.startswith("/?"):
            try:
                with open(INDEX_HTML, "rb") as fh:
                    body = fh.read()
            except FileNotFoundError:
                self._send(HTTPStatus.INTERNAL_SERVER_ERROR, b"index.html missing", "text/plain")
                return
            self._send(HTTPStatus.OK, body)
            return
        if self.path == "/status":
            self._send(HTTPStatus.OK, _status_page())
            return
        if self.path == "/setup":
            self._send(HTTPStatus.METHOD_NOT_ALLOWED, b"Use POST.", "text/plain")
            return
        self._send(HTTPStatus.NOT_FOUND, b"Not found", "text/plain")

    def do_POST(self):  # noqa: N802
        if self.path != "/setup":
            self._send(HTTPStatus.NOT_FOUND, b"Not found", "text/plain")
            return
        length = int(self.headers.get("Content-Length", "0") or 0)
        if length <= 0 or length > 1_000_000:
            self._send(HTTPStatus.BAD_REQUEST, b"Bad request", "text/plain")
            return
        raw = self.rfile.read(length).decode("utf-8", errors="replace")
        form = parse_qs(raw, keep_blank_values=True)
        values, errors = _validate(form)
        if errors:
            self._send(HTTPStatus.BAD_REQUEST, _error_page(errors))
            return
        try:
            _write_env_file(values)
        except OSError as exc:
            self._send(
                HTTPStatus.INTERNAL_SERVER_ERROR,
                f"Failed to write config: {exc}".encode("utf-8"),
                "text/plain",
            )
            return
        _spawn_install()
        self._send(HTTPStatus.OK, _running_page())


def main() -> int:
    os.makedirs(STATE_DIR, exist_ok=True)
    addr = ("0.0.0.0", 80)
    httpd = HTTPServer(addr, Handler)
    sys.stderr.write(f"[firstboot] listening on {addr[0]}:{addr[1]}\n")
    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        pass
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
