name: Shellcheck

on:
  push:
    paths:
      - 'scripts/**'
      - 'install.sh'
      - 'build/**'
      - 'firstboot/**'
  pull_request:
    paths:
      - 'scripts/**'
      - 'install.sh'
      - 'build/**'
      - 'firstboot/**'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Shellcheck scripts
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: './scripts'
          severity: warning

      - name: Shellcheck install.sh
        uses: ludeeus/action-shellcheck@master
        with:
          additional_files: 'install.sh'
          severity: warning

      - name: Shellcheck build stage scripts
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: './build/stage-travel-router'
          severity: warning

      - name: Shellcheck firstboot scripts
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: './firstboot'
          severity: warning
        continue-on-error: true
